// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, mes, port;

  express = require('express');

  app = express.createServer(express.logger());

  mes = "<p>hello world?</p>";

  app.get('/', function(req, resp) {
    return resp.render('index.ejs', {
      locals: {
        mes: mes
      }
    });
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
  });

}).call(this);
